export const SET_PAGETITLE = 'SET_PAGETITLE';

export const SET_ENDPOINT1 = 'SET_ENDPOINT1';
export const CLEAR_ENDPOINT1 = 'CLEAR_ENDPOINT1';

export const SET_ENDPOINT2 = 'SET_ENDPOINT2';
export const CLEAR_ENDPOINT2 = 'CLEAR_ENDPOINT2';
